{
 "title": "Restic Exporter",
 "description": "Restic statistics dashboard",
 "tags": [ "system" ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Repository Check",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without (pod, instance) (restic_check_success)"
    }
   ]
  },
  {
   "title": "Last Scraped",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max without (pod, instance, endpoint) (restic_last_scrape_timestamp_seconds)"
    }
   ]
  },
  {
   "title": "Backup Statistics",
   "type": "table",
   "description": "Comprehensive backup statistics",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "restic_backup_timestamp * 1000", "legendFormat": "{{client_hostname}}" },
    {
     "expr": "(time() - restic_backup_timestamp) / 86400",
     "legendFormat": "{{client_hostname}}"
    },
    {
     "expr": "sum by (client_hostname, client_version, snapshot_paths) (restic_backup_files_total)",
     "legendFormat": "{{client_hostname}}"
    },
    {
     "expr": "sum by (client_hostname, snapshot_paths) (restic_backup_size_total)",
     "legendFormat": "{{client_hostname}}"
    },
    { "expr": "restic_backup_snapshots_total", "legendFormat": "{{client_hostname}}" },
    {
     "expr": "restic_backup_first_timestamp * 1000",
     "legendFormat": "{{client_hostname}}"
    }
   ]
  },
  {
   "title": "Total backup size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(client_hostname,snapshot_paths) (restic_backup_size_total)",
     "legendFormat": "{{client_hostname}} - {{snapshot_paths}}"
    }
   ]
  },
  {
   "title": "Total backup files",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by(client_hostname,snapshot_paths) (restic_backup_files_total)",
     "legendFormat": "{{client_hostname}} - {{snapshot_paths}}"
    }
   ]
  },
  {
   "title": "Total snapshot count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(client_hostname,snapshot_paths) (restic_backup_snapshots_total)",
     "legendFormat": "{{client_hostname}} - {{snapshot_paths}}"
    }
   ]
  },
  {
   "title": "Command Durations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max without (pod, instance, endpoint) (restic_snapshots_restore_size_duration_seconds)",
     "legendFormat": "Snapshots Restore Size Duration"
    },
    {
     "expr": "max without (pod, instance, endpoint) (restic_snapshots_duration_seconds)",
     "legendFormat": "Snapshots Duration"
    },
    {
     "expr": "max without (pod, instance, endpoint) (restic_repository_check_duration_seconds)",
     "legendFormat": "Repository Check Duration"
    },
    {
     "expr": "max without (pod, instance, endpoint) (restic_raw_data_stats_duration_seconds)",
     "legendFormat": "Raw Data Stats Duration"
    },
    {
     "expr": "max without (pod, instance, endpoint) (restic_scrape_duration_seconds)",
     "legendFormat": "Scrape Duration"
    }
   ]
  },
  {
   "title": "Repository Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max without (pod, instance, endpoint) (restic_repository_total_size_bytes)",
     "legendFormat": "Repository Total Size"
    },
    {
     "expr": "max without (pod, instance, endpoint) (restic_repository_total_uncompressed_size_bytes)",
     "legendFormat": "Repository Uncompressed Size"
    }
   ]
  },
  {
   "title": "Compression Ratio",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without (pod, instance, endpoint) (restic_compression_ratio)",
     "legendFormat": "Compression Ratio"
    }
   ]
  }
 ]
}