{
 "title": "Restic Exporter",
 "description": "Restic statistics dashboard",
 "tags": [ "system" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Repository Check",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "restic_check_success" }
   ]
  },
  {
   "title": "Backup Statistics",
   "type": "table",
   "description": "Comprehensive backup statistics",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "restic_backup_timestamp * 1000", "legendFormat": "{{client_hostname}}" },
    {
     "expr": "(time() - restic_backup_timestamp) / 86400",
     "legendFormat": "{{client_hostname}}"
    },
    {
     "expr": "sum by (client_hostname, client_version, snapshot_paths) (restic_backup_files_total)",
     "legendFormat": "{{client_hostname}}"
    },
    {
     "expr": "sum by (client_hostname, snapshot_paths) (restic_backup_size_total)",
     "legendFormat": "{{client_hostname}}"
    },
    { "expr": "restic_backup_snapshots_total", "legendFormat": "{{client_hostname}}" }
   ]
  },
  {
   "title": "Total backup size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(client_hostname,client_username) (restic_backup_size_total)",
     "legendFormat": "{{client_hostname}}"
    }
   ]
  },
  {
   "title": "Total backup size",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "restic_backup_size_total", "legendFormat": "{{client_hostname}}" }
   ]
  },
  {
   "title": "Total backup files",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(client_hostname,client_username) (restic_backup_files_total)",
     "legendFormat": "{{client_hostname}}"
    }
   ]
  },
  {
   "title": "Total snapshot count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(client_hostname,client_username) (restic_backup_snapshots_total)",
     "legendFormat": "{{client_hostname}}"
    }
   ]
  }
 ]
}